services:
  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: api-gateway-${APP_ENV:-dev}
    ports:
      - "8080:8080"
    env_file:
      - ../env/${APP_ENV:-dev}.env
    environment:
      APP_ENV: ${APP_ENV:-dev}
    extra_hosts:
      - "host.docker.internal:host-gateway"
